### ISSUE TITLE
Add Content Management System

### ISSUE THREAD

**Issue by phillipahereza** [TakwimuAfrica/TAKWIMU#11]
## Description

After initially considering [Django CMS](https://www.django-cms.org), we will instead integrate [Wagtail](https://github.com/wagtail/wagtail/tree/v2.0) into TAKWIMU to offer a way to manage the content published on this platform including country profiles, blogs and site pages.

Some of the reasons choosing Wagtail over Django CMS include:

1. StreamField offers interesting functionality similar to proto's card + stream approach to content.
2. Being more recent, could offer newer techniques of problem solving.

Read more on choice here: http://www.djangopaths.com/why-did-i-choose-wagtail/#Integrating%20custom%20models%20and%20templates

## Links
- [Wagtail](https://github.com/wagtail/wagtail/tree/v2.0)

## Tasks
- [ ] Add wagtail to requirements
- [ ] Write tests
- [ ] Write documentation
- [ ] User test

**Comment by DavidLemayian** [comment]
Closed for this instead - https://github.com/CodeForAfricaLabs/HURUmap/issues/2
