### ISSUE TITLE
[BUG] invalid literal for int() with base 10

### ISSUE THREAD

**Issue by mtuchi** [TakwimuAfrica/TAKWIMU#130]
**Describe the bug**
When editing a profile page when you save the profile page you get the `invalid literal for int() with base 10: ` error

**To Reproduce**
1. Go to 'Profiles'
2. Click on 'Edit profile'
3. Scroll down to 'Save draft' the click 'Save draft'

**Expected behavior**

**Screenshots**
![peek 2018-07-03 09-23](https://user-images.githubusercontent.com/6592749/42202400-f414b2d8-7ea3-11e8-856c-d4e289b9f12c.gif)

**Desktop (please complete the following information):**
 - OS: Bunsen labs
 - Browser: Chrome
 - Version: 67.0.3396.99 (Official Build) (64-bit)

**Additional context**

- At the moment of writing it happens to only two `country profiles`

**Comment by DavidLemayian** [comment]
Fixed by deleting Wakanda page. Might be that there is no safety when sections aren't set.
