### ISSUE TITLE
[ADMIN] Add terms of use + privacy policy

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#164]
**Is your feature request related to a problem? Please describe.**
We currently don't have views + edit interface for the terms of use and privacy policies.

**Describe the solution you'd like**
An edit interface and the respective views for terms of use + privacy policies.

**Describe alternatives you've considered**
We should do this as Markdown files that are use a Markdown `include` template tag.

**Files**
- https://app.zeplin.io/project/5ae37a224a28f19738a929fb/screen/5b15fcc9d15b50b66a07e21a

**Task**
- [ ] Implement the terms of use page from zaang

**Comment by kilemensi** [comment]
I've added respecting settings via #202 @DavidLemayian

**Comment by DavidLemayian** [comment]
@kilemensi Given feedback. We need markdown template tag and should not be in CMS settings as we don't want changes for those files to be easy. They're legal documents so need a lot more balances and checks for update.

**Comment by DavidLemayian** [comment]
@kilemensi Just noticing the issue had not been updated to reflect this change.

@nerdlet let's keep an eye on any documentation updates that need to be done from in-person convo. Otherwise let's try keep everything in writing to avoid this confusions.
