### ISSUE TITLE
[CONTENT] Add relevant content to replace dummy data

### ISSUE THREAD

**Issue by nerdlet** [TakwimuAfrica/TAKWIMU#187]
## Description
Remove all dummy data(Lorem ipsum) from takwimu and add all relevant corresponding data for the following sections:
-Contact page
-Partnership
-Update section

## Screenshot

<img width="1095" alt="partnership" src="https://user-images.githubusercontent.com/3693563/42756607-8f30b102-8905-11e8-8614-a2efde1ccc9c.png">

<img width="1250" alt="update" src="https://user-images.githubusercontent.com/3693563/42756611-964ac446-8905-11e8-8687-9350cbe6824a.png">

<img width="1253" alt="contact" src="https://user-images.githubusercontent.com/3693563/42756623-a4243c5a-8905-11e8-89ea-9545b2a5c6d4.png">

## Files
https://docs.google.com/spreadsheets/d/178Ujf1T8q43t-yFySNktQFMj7V8Q9lozF2c2A6pFwls/edit?usp=sharing

**Comment by DavidLemayian** [comment]
@nerdlet Please breakdown the changes to be tasks. When changed, please replace the row with link to Github Issue.
