### ISSUE TITLE
[PROFILES] Fix anchor navigation padding from top

### ISSUE THREAD

**Issue by nerdlet** [TakwimuAfrica/TAKWIMU#188]
## Description
The anchor in the topic section is a tad bit off. A user is not directed to the actual start of the topic section, rather to either the description or the indicator of that section. Same applies for the horizontal topic navigation on the country profile page.

This is primarily because we have the fixed top navbar that isn't accounted for when navigation to anchor id happens.

## Screenshots
TOC Navigation
![image](https://user-images.githubusercontent.com/3693563/42691678-b30ecd9e-86b1-11e8-8fbe-ad1ab46f85d3.png)

Horizontal Navigation
![image](https://user-images.githubusercontent.com/3693563/42691736-ea0a40d0-86b1-11e8-91c5-6859e6e2c74f.png)

## Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] ???
- [ ] ???
- [ ] ???

**Comment by kilemensi** [comment]
Fixed via #300
