### ISSUE TITLE
[FIX] Subscribe to RSS feed

### ISSUE THREAD

**Issue by nerdlet** [TakwimuAfrica/TAKWIMU#191]
## Description
Fix the link to the Subscribe to RSS 
https://dev.takwimu.africa/feed/

## Screenshots
![image](https://user-images.githubusercontent.com/3693563/42692505-9fd7734a-86b4-11e8-9d70-e5df757cd4bc.png)

## Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] ???

**Comment by DavidLemayian** [comment]
@nerdlet What's broken here?

**Comment by nerdlet** [comment]
@DavidLemayian The **subscribe to RSS feed** link is redirecting to the xml file and not the actual rss feed for visitors to subscribe to

**Comment by DavidLemayian** [comment]
@nerdlet That's what's the intended action. RSS feeds are XML formatted. Closing this but feel free to reopen if I've misunderstood the issue.
