### ISSUE TITLE
Front end initial setup

### ISSUE THREAD

**Issue by nerdlet** [TakwimuAfrica/TAKWIMU#20]
## Description
Determine the blue accent color of takwimu

## Tasks
- [x] Color pallet
- [x] Icons setup
- [x] Font setup
- [x] Bootstrap

## Color Palette

![newcolor](https://user-images.githubusercontent.com/6592749/40375465-5c61485e-5df4-11e8-8a5b-72ffdf2cef6c.png)

**Comment by DavidLemayian** [comment]
@nerdlet + @mtuchi Please use the blue from the logo.

**Comment by DavidLemayian** [comment]
@nerdlet + @mtuchi these look fine. Thanks. Any use of whites?
