### ISSUE TITLE
[FEATURE] Datawrapper visual styling

### ISSUE THREAD

**Issue by seangp** [TakwimuAfrica/TAKWIMU#219]
## Description
Not sure how much control you have over these, but if possible, it would be good to try improve them visually by:

* Removing the social icons (this functionality is available under the share action)
* Adding a horizontal rule below the description (similar to the design). This will help delineate the description and visual better as it currently clashes with the text within the data visual

## Screenshots
<img width="888" alt="screen shot 2018-07-22 at 00 36 46" src="https://user-images.githubusercontent.com/4629781/43040872-f9598c8e-8d47-11e8-9164-d2c01920049d.png">

**Comment by DavidLemayian** [comment]
Unfortunately no way to do this on the platform itself.
