### ISSUE TITLE
[BUG] Update "Our Services" Navbar + Page

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#228]
**Describe the bug**
We have content for the our services navbar + page.

https://docs.google.com/spreadsheets/d/1i5Wn4M7WymRHcri5tg4FiTR7aqJ04j38py6Zhlv2yqo/edit#gid=0

**Comment by mtuchi** [comment]
@DavidLemayian do i feed in the data in CMS in `dev.takwimu.africa` or ?

**Comment by DavidLemayian** [comment]
@mtuchi Content updates should be done by the comms team if it's available to edit on CMS.
