### ISSUE TITLE
[NAVBAR] Allow ordering of support services in CMS

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#247]
**Is your feature request related to a problem? Please describe.**
Currently there is no easy ways for editors to order support services links in the navbar.

**Describe the solution you'd like**
I'd want an easy way to order these.

**Describe alternatives you've considered**
<A clear and concise description of any alternative solutions or features you've considered.>

**Additional context**
![skitch](https://user-images.githubusercontent.com/877919/43095472-9a0022e8-8ebe-11e8-94b8-d984b10882b6.png)

**Comment by kilemensi** [comment]
Fixed via #277
