### ISSUE TITLE
[HOMEPAGE] Define Support Services in Settings

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#258]
**Is your feature request related to a problem? Please describe.**
I would like to order the personae on the homepage.

**Describe the solution you'd like**
A way to edit and order persona in the CMS

**Describe alternatives you've considered**
Using a wagtail list panel or stream field panel in the editor interface.

**Additional context**
The personas are already created in the Support Services tabs so some considered steps:
1. Create the settings model (or models) that allows for all the support services to be defined from settings.
2. Migrate the support services content to the new model and fix frontend references.
3. Send out message to the site editors that this has changed.

**Comment by DavidLemayian** [comment]
Related #247

**Comment by africapractice** [comment]
Just to clarify @DavidLemayian this will:
- separate persona and support services in the cms and front end
- enable ordering of persona and of support services in the cms
correct?

**Comment by kilemensi** [comment]
Hey @africapractice.

PR #277 moves the **creation** and **ordering** of support services (persona, standard and premium services) into `Support Services` under `Settings` in the dashboard.

If they do need to be separated in the back-end (dashboard) as well, lets create a separate issue to track that (they're already separated in the front end I believe).

Fixed via #277.
