### ISSUE TITLE
Persona Titles break if more than 10 characters

### ISSUE THREAD

**Issue by africapractice** [TakwimuAfrica/TAKWIMU#264]
**Describe the bug**
The titles of the homepage personae when viewed in their respective drop down panels break mid word if more than 10 characters long

**To Reproduce**
1. Go to `about`
2. Click on Researchers and Analysts persona
3. See the persona title

**Expected behavior**
The titles of the persona need to appear properly formatted

**Screenshots**
![takwimu01](https://user-images.githubusercontent.com/14904333/43250556-8d8fb00c-90b5-11e8-8767-d99a9bddc431.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Bunsen labs]
 - Browser [e.g. Firefox Quantum]
 - Version [e.g. 61.0.1 (64-bit)]

**Additional context**
Zeplin [design](https://app.zeplin.io/project/5b1a4192c1a8233544fcc66a/screen/5b43e704b58d5fe701538469)
Reduce font size?

**Comment by DavidLemayian** [comment]
@mtuchi what suggestion might you have for this?

**Comment by mtuchi** [comment]
@DavidLemayian 
Am trying couple of text-wrap technique using css, i will let you know once i have a solid answer
