### ISSUE TITLE
Change 'Go to Forum' CTA against topics

### ISSUE THREAD

**Issue by africapractice** [TakwimuAfrica/TAKWIMU#268]
**Is your feature request related to a problem? Please describe.**
This ticket is described in the attached 
![takwimu](https://user-images.githubusercontent.com/14904333/43253197-4b1bedf6-90bc-11e8-8100-93f9301b7870.png)
screenshot

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by DavidLemayian** [comment]
@africapractice I think you might have misread what's on the Zaang Design. We've replaced "89 comment" with "go to forum":

<img width="358" alt="screen shot 2018-07-26 at 13 56 41" src="https://user-images.githubusercontent.com/877919/43258583-f88eb1d4-90db-11e8-8e70-72baae272c84.png">

You'll notice that we're actually solving for the "there will likely be nothing there in the early days" by  doing this.

I'll close this issue but feel free to reopen if misunderstood.

**Comment by africapractice** [comment]
Thanks @DavidLemayian - I do se what you mean but still think 'go to forum' is not a great CTA - can we please re-open and replace with Clemence's suggestion of 'Have your say'. Thanks

**Comment by DavidLemayian** [comment]
@africapractice This has been changed.
