### ISSUE TITLE
Homepage community Forum link is broken

### ISSUE THREAD

**Issue by africapractice** [TakwimuAfrica/TAKWIMU#270]
**Describe the bug**
From homepage - join the discussion - community forum - the link is broken 

**To Reproduce**
Steps to reproduce the behavior: - as above

**Expected behavior**
teh link shoudl take user to https://takwimu.zendesk.com/hc/en-us/community/topics

**Screenshots**
![banners_and_alerts_and_takwimu](https://user-images.githubusercontent.com/14904333/43311820-654f7dd8-9183-11e8-9d7c-74f97ae58666.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kilemensi** [comment]
Fixed.

Community Forum link can now be configured in the Dashboard (`Settings` >> `Support` >> `Community`)
