### ISSUE TITLE
Enable ordering of Persona in Homepage UI

### ISSUE THREAD

**Issue by africapractice** [TakwimuAfrica/TAKWIMU#272]
**Is your feature request related to a problem? Please describe.**
We are focusing on priority personae first - this needs to be reflected in UI

**Describe the solution you'd like**
Enable ordering of the Persona on homepage

Result should be 
![takwimu](https://user-images.githubusercontent.com/14904333/43316346-fbe017f0-9190-11e8-8fc5-c72c252d2a13.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by africapractice** [comment]
This is a high priority hot fix for UAT launch

**Comment by DavidLemayian** [comment]
Duplicate of #258, #247
