### ISSUE TITLE
[TOPICS] Create Topics Page

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#291]
**Is your feature request related to a problem? Please describe.**
We have designs for the topics page.

**Describe the solution you'd like**
An implemented topics page according to designs.

**Describe alternatives you've considered**
Web: https://zpl.io/bzWEmDl
App: zpl://screen?sid=5b438bfcd49f418c65628b1a&pid=5b1a4192c1a8233544fcc66a

**Additional context**
<img width="739" alt="screen shot 2018-07-31 at 18 13 49" src="https://user-images.githubusercontent.com/877919/43468796-7fa73adc-94ed-11e8-8e5c-ee30a24d7240.png">

**Comment by kilemensi** [comment]
This looks good to go @DavidLemayian.

Just confirm if the Navbar is heading, i.e. **Topic** is good enough. **Data by Topic** seems to be too long causing line break.
