### ISSUE TITLE
[SDGs] Create SDG landing page

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/Takwimu#294]
**Is your feature request related to a problem? Please describe.**
Currently there is no landing page for SDGs created at #293.

**Describe the solution you'd like**
Landing page according to designs.

**Describe alternatives you've considered**
Web: https://zpl.io/blpw5J5
App: zpl://screen?sid=5b438c02d51487cc5f85b08f&pid=5b1a4192c1a8233544fcc66a

**Additional context**
Relate to #70, #293

<img width="730" alt="screen shot 2018-07-31 at 18 26 08" src="https://user-images.githubusercontent.com/877919/43469965-19968aa6-94f0-11e8-8fa0-faffaa5883f2.png">

**Comment by phillipahereza** [comment]
@mtuchi progress on this?

**Comment by mtuchi** [comment]
@phillipahereza let me create a PR for this, 
Most task are done from the UI point of view
