### ISSUE TITLE
[FIXTURES] Improve fixtures use

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/Takwimu#296]
**Is your feature request related to a problem? Please describe.**
Fixtures are a great way to have the same data in development but documentation is slightly sparse on usage and we might have "old" fixtures (schema + data)

**Describe the solution you'd like**
A couple of things I'd like:

1. Review the fixtures currently available
2. Add easy way to load all fixtures during development
3. An easy way to create fixtures from production data
4. Documentation on this improved in `README.md`

**Describe alternatives you've considered**
TODO: A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
TODO: Add any other context or screenshots about the feature request here.

**Comment by kilemensi** [comment]
The ability to do a migration based on fixture (useful for providing initial data) has already been added in #343 .

**Comment by DavidLemayian** [comment]
Thanks @kilemensi. Is the documentation in `README.md` updated for this?

Also, would a better approach be to use test db instead of fixtures?
