### ISSUE TITLE
[HOMEPAGE] Send Your Comments button is broken

### ISSUE THREAD

**Issue by africapractice** [TakwimuAfrica/TAKWIMU#302]
**Describe the bug**

**To Reproduce**
1. Go to Homepage
2. Click on  Carousel / We want your feedback / send your comments

**Expected behavior**
This button should take the user to https://takwimu.zendesk.com/hc/en-us/community/topics

**Screenshots**
<img width="1174" alt="takwimu" src="https://user-images.githubusercontent.com/14904333/43524276-cbf304e4-9596-11e8-80b5-1ff235600c7f.png">
<img width="1171" alt="page_not_found_at__contact_us" src="https://user-images.githubusercontent.com/14904333/43524320-e6da3552-9596-11e8-961a-641e7b18d43f.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by DavidLemayian** [comment]
Fixed.
