### ISSUE TITLE
[NAVBAR] When Click "About Us", go to about page

### ISSUE THREAD

**Issue by NatalieMaule** [TakwimuAfrica/TAKWIMU#306]
When I click on "About Us" on the top navigation bar it opens a page which has a sentence about Takwimu on the left hand side and then 4 clickable options on the right: "About Takwimu", "Support Services", "Contact Us" and "Dashboard (admin)." I don't see why I should need to click "About Takwimu" twice to get to the full copy (see second screenshot below - text on the white background) - it should be visible immediately on the "About Us" page when you click from the homepage. "Support Services" is not part of "About Us" and should sit on the "Our Services" page and there is also a "Contact Us" option on the top navigation bar so not sure why it would sit under "About Us". I don't think visitors to the site should see the "Dashboard (admin)" option so can we remove this please.

![image](https://user-images.githubusercontent.com/42028181/43641334-2d83c25e-971b-11e8-8a76-eb43f4e274ff.png)
![image](https://user-images.githubusercontent.com/42028181/43641345-375cd77a-971b-11e8-8800-c5f1fe0dd84a.png)

**Comment by DavidLemayian** [comment]
@NatalieMaule That's a lot to digest so addressing each point:

> I don't see why I should need to click "About Takwimu" twice to get to the full copy. 

Agreed. We're making the "About Us" button in navbar clickable

> "Support Services" is not part of "About Us" and should sit on the "Our Services" page and there is also a "Contact Us" option on the top navigation bar so not sure why it would sit under "About Us"

Repeating links is a good design practice. You give more entry points / user journeys to the content. Both options are actually pretty relevant here so good to have but let us know if you points to the contrary.

>  I don't think visitors to the site should see the "Dashboard (admin)" option

We're pretty confident visitors have an issue with this and ee do intend to give them access to login in future so it's good for them to know a backend exists.
