### ISSUE TITLE
[BUG] Fix support services page

### ISSUE THREAD

**Issue by mtuchi** [TakwimuAfrica/Takwimu#323]
**Describe the bug**
Getting an error when opening `Support Services` in wagtail (CMS)

**To Reproduce**
1. Go to '[Login to dashboard](https://takwimu.africa/dashboard/)'
2. Click on 'Settings'
3. Then click `Support services`

**Expected behavior**
You should see an error that says.
```
UnicodeEncodeError at /dashboard/settings/takwimu/supportservicessetting/1/
'ascii' codec can't encode character u'\xfc' in position 1: ordinal not in range(128)
```
**Screenshots**
![error](https://user-images.githubusercontent.com/6592749/43831782-e9ae43fa-9b0d-11e8-8dcd-d10f81e8ef00.gif)

**Desktop (please complete the following information):**
 - OS: [e.g. Bunsen labs]
 - Browser [e.g. Firefox Quantum]
 - Version [e.g. 61.0.1]

**Comment by kilemensi** [comment]
@phillipahereza, any progress on this? We really need this fixed today.

**Comment by phillipahereza** [comment]
@kilemensi the error comes from the fontawesome, for now, the easiest solution would be to remove the offending icon https://fontawesome.com/icons/buromobelexperte?style=brands. Still trying to find a solution though

**Comment by kilemensi** [comment]
Cool @phillipahereza. But why does it work perfectly when running locally?

Anyways, if removing that icon works then lets remove it for now and create a separate issue to track it because currently it's impossible to edit some of the settings in takwimu.africa and we need to upload the country profile PDFs today.

**Comment by phillipahereza** [comment]
@kilemensi your requirements are probably not updated, @KhadijaMahanga updated the django-awesome package to Fontawesome 5.2 and that's when the issue started

**Comment by phillipahereza** [comment]
@kilemensi done, for testing purposes please reinstall your dependencies especially django-fontawesome and confirm that it now works

**Comment by kilemensi** [comment]
Yeah, let me test both before and after upgrading & will let you know @phillipahereza.

**Comment by phillipahereza** [comment]
Hey @kilemensi did you test this?

**Comment by kilemensi** [comment]
@phillipahereza Yes! The fix worked and was pushed. Thanks.

But I think we need a permanent solution since there might be a lot more of these types of icons in future and handling each one manual might be a problem.
