### ISSUE TITLE
[SEARCH] Implement my collection section on search results page

### ISSUE THREAD

**Issue by mtuchi** [TakwimuAfrica/Takwimu#332]
## Description

Design my collection on the sidebar of the search results page.

## Screenshots

![screenshot_2018-09-11_09-50-25](https://user-images.githubusercontent.com/6592749/45342970-22eeab00-b5a8-11e8-9a5d-1da4598a55db.png)

## Files
[Zeplin Designs](https://app.zeplin.io/project/5b1a4192c1a8233544fcc66a/screen/5b4405a75792d5de5f566922)

## Tasks
Use the zeplin file attached on this issue for further reference :arrow_up_small: 
- [ ] Design my collections list items with badge 
- [ ] Add new collection button

## Related issue
#331

**Comment by DavidLemayian** [comment]
This depends on implementing the "My Collection" feature.
