### ISSUE TITLE
[SEARCH] Create search page

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#337]
**Is your feature request related to a problem? Please describe.**
We currently have no easy way to search through the site's content.

**Describe the solution you'd like**
I would like a search page with results.

**Describe alternatives you've considered**
N/A

**Additional context**
This issue is specific to backend tasks that will then serve as the basis for the frontend work:

- [ ] Create templates
- [ ] Create view that returns mock data

**Comment by kilemensi** [comment]
Fixed by #338
