### ISSUE TITLE
Add Kenya to Takwimu Geographies

### ISSUE THREAD

**Issue by phillipahereza** [TakwimuAfrica/TAKWIMU#358]
## Description
Add geographies for the phase 2 countries i.e. Kenya, Ethiopia, Uganda, DRC, South Africa, Zambia, Burkina Faso 

## To Reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.

## Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Source the geojson for the countries
- [ ] Add geographies to wazimap_geography.sql

**Comment by phillipahereza** [comment]
@kilemensi but would it hurt to have all the geographies on there and have it done once and for all?

**Comment by kilemensi** [comment]
No it wouldn't hurt @phillipahereza. My thinking was to avoid having empty countries on HURUmap that have neither profile analysis or data, hence aligning profile analysis, data & HURUmap releases.

**Comment by phillipahereza** [comment]
@kilemensi hadn't thought about that, in that case, can we have a checklist of the remaining countries and check the ones we add and close the issue when all countries are added? Or we create an issue for each country?

**Comment by kilemensi** [comment]
I think the second option is better @phillipahereza since we can align issues with milestones/projects rather than having one giant issue spanning multiple milestones.

**Comment by phillipahereza** [comment]
Alright @kilemensi I'll change this PR to Kenya geography. Any idea on the milestone I should attach?

**Comment by phillipahereza** [comment]
Closed via #381
