### ISSUE TITLE
Multiple Widgets per Indicator

### ISSUE THREAD

**Issue by kilemensi** [TakwimuAfrica/TAKWIMU#371]
**Is your feature request related to a problem? Please describe.**
It's currently impossible to have more than one widget per indicator. By widget, we mean a viz, an embed, a document, etc. Hence it's impossible to have "multiple views" of the same indicator data.

**Describe the solution you'd like**
For each indicator, one should be able to add more than one widget.

**Describe alternatives you've considered**

 * [ ] Convert the current `IndicatorsBlock` into `IndicatorWidgetsBlock`,
 * [ ] Create a new `IndicatorBlock` to contain `IndicatorWidgetsBlock`, and
 * [ ] Modify `TopicBlock` to contain the new `IndicatorBlock` instead of the old `IndicatorsBlock`.

**Additional context**
The new indicator should:

 * [ ] Contain a way of indicating which widget is the main Visual widget or primary widget that would be displayed by default, and
 * [ ] Allow lazy loading of heavy widgets like documents (if possible).

**Comment by phillipahereza** [comment]
@kilemensi on here, what about we leave things as is and add a many-to-many relationship on the indicators so that we can have a related_indicators kind of thing?

**Comment by kilemensi** [comment]
That would mean all indicators would still appear on the indicators list/menu which is not something we want @phillipahereza. I think the idea is to separate the indicator from its many possible *appearances*.

Can you achieve it through relations?

**Comment by phillipahereza** [comment]
@kilemensi not sure if that can be achieved through relations, but I'll go ahead and implement ☝️
