### ISSUE TITLE
HURUmap Widget

### ISSUE THREAD

**Issue by kilemensi** [TakwimuAfrica/TAKWIMU#372]
**Is your feature request related to a problem? Please describe.**
Currently all visualization in [Takwimu](https://takwimu.africa) are done using [Datawrapper](https://datawrapper.de). [HURUmap](https://hurumap.org) should be used instead.

**Describe the solution you'd like**
A new indicator widget that uses HURUmap should be added to the widgets list and become the main visualization widget.

**Describe alternatives you've considered**
There are many approaches that this could be achieved. From the do nothing approach (use the html embed widget to embed HURUmap charts) to making the whole country profile analysis page one of HURUmap page and the widget would hence have access to all the HURUmap data for a particular country and it would only need to keep track of name of data and what kind of chart to display.

But for our first version, lets base the HURUmap widget on the embed functionality already implemented on HURUmap as well as HTML indicator already implemented in Takwimu. The HURUmap embed code is as the one shown below:
```html
<iframe id="cr-embed-region-22-demographics-age_group_distribution"
        class="census-reporter-embed"
        src="https://tanzania.hurumap.org/embed/iframe.html?geoID=region-22&geoVersion=2009&chartDataID=demographics-age_group_distribution&dataYear=2011&chartType=histogram&chartHeight=200&chartQualifier=&chartTitle=Population+by+age+range&initialSort=&statType=scaled-percentage"
        frameborder="0"
        width="100%"
        height="300"
        style="margin: 1em; max-width: 720px;"></iframe>
<script src="https://tanzania.hurumap.org/static/js/embed.chart.make.js"></script>
```
The most relevant information is in the `src` attribute of the `iframe` specifically: *chartDataID*, *chartType*, *chartTitle*, and *statType*. By varying these, one can change the data for the chart (*chartDataID*), type of the chart (*chartType* and *statType*), as well as the title.

Hence:

 * [ ] Maintain a list of names of all available data distributions,
 * [ ] Create a new `HURUmap` indicator type that:
      * Has a list of the available data distributions (*chartDataID*),
      * type (*chartType*), a list of available chart types in HURUmap,
      * scale (*statType*), alllowed scale types in HURUmap,
      * title (*chartTitle*),
 * [ ] Use the above settings and the embed `iframe` template above to generate the requied chart as an HTML embed.

**Comment by phillipahereza** [comment]
@kilemensi Takwimu already allows for adding of embeds, do we need to create a new embed widget specifically for the HURUmap Visualizations?

**Comment by kilemensi** [comment]
That's the alternative solution number 1 @phillipahereza. I recognize it's strength but the downside is that it's a very manual process. Can't we have anything on the dashboard that can help automate it?

If all fails then yeah, this will be our last resort.
