### ISSUE TITLE
Github CI Errors

### ISSUE THREAD

**Issue by kilemensi** [TakwimuAfrica/TAKWIMU#384]
## Description
Seems like some tests always fail with error `Manifest not found`

## Screenshots
![screenshot from 2018-09-19 11-09-30](https://user-images.githubusercontent.com/1779590/45739938-ca995800-bbfc-11e8-8cc6-f41709e9603e.png)

## To Reproduce
Create a PR and watch the CI tests.

**Comment by phillipahereza** [comment]
Fixed via #382
