### ISSUE TITLE
Improve Search

### ISSUE THREAD

**Issue by phillipahereza** [TakwimuAfrica/Takwimu#426]
**Is your feature request related to a problem? Please describe.**
- Currently, search returns the 'whole' widget that contains the searched phrase
![search_issues](https://user-images.githubusercontent.com/13383422/47358130-8bfe2e00-d6d1-11e8-8c35-dd6d27018129.gif)

- Search is a bit slow especially when showing results with visualizations
- Update the filters to be backend driven 

**Describe the solution you'd like**
- To improve performance, show a simple view first; one that doesn't make calls to an external service and lazy load the other vizs

**Additional context**
None

**Comment by kilemensi** [comment]
Opened in internal tracker #161446662
