### ISSUE TITLE
[SERVICES] Implement Support Services Page

### ISSUE THREAD

**Issue by phillipahereza** [TakwimuAfrica/TAKWIMU#81]
## Description
The data services page implements both the normal page layout and data by priority section.

The order for this is laid out in the screenshots below.

## Screenshots

**Hero:**
<img width="724" alt="screen shot 2018-06-25 at 16 51 08" src="https://user-images.githubusercontent.com/877919/41854181-3f79e19c-7898-11e8-96fb-7f7ccb0bc297.png">

**Data by Priority:**
<img width="722" alt="screen shot 2018-06-14 at 15 57 59" src="https://user-images.githubusercontent.com/13383422/41413873-16ae2f9c-6fed-11e8-877a-5262971b5507.png">

**Get In Touch**
<img width="723" alt="screen shot 2018-06-25 at 16 52 36" src="https://user-images.githubusercontent.com/877919/41854243-6022f0dc-7898-11e8-8f6b-073591158105.png">

## Files

- Data Services : https://app.zeplin.io/project/5ae37a224a28f19738a929fb/screen/5b1a4341a2d56631598c8840
- Data by Priority: https://app.zeplin.io/project/5ae37a224a28f19738a929fb

- Data Services page: https://github.com/TakwimuAfrica/TAKWIMU/blob/develop/takwimu/templates/takwimu/about/data-services.html
- Data By Priority Section: ?

## Tasks

- [x] Style according to designs on Zeplin

**Comment by mtuchi** [comment]
@DavidLemayian should i refactor this issue ?

**Comment by DavidLemayian** [comment]
@mtuchi I'll refine it according to the new direction on the Zaang channel.
