### ISSUE TITLE
Add RSS Feed

### ISSUE THREAD

**Issue by DavidLemayian** [TakwimuAfrica/TAKWIMU#91]
## Description
Add RSS feed that we can point people to to subscribe for updates.

## Files
- https://docs.djangoproject.com/en/1.9/ref/contrib/syndication/
- https://chrxr.com/adding-rss-feed-wagtail-site/

## Tasks

- [ ] Follow steps in articles above

**Comment by phillipahereza** [comment]
@DavidLemayian since we're pulling stories from Medium, we could just add the Medium RSS feed

**Comment by phillipahereza** [comment]
@DavidLemayian do you mean RSS for the country reports? Because for the stories we could use the Medium RSS feed
