### ISSUE TITLE
[DOCUMENTATION] SRS - Security Requirements

### ISSUE THREAD

**Issue by yazminjumaali** [TakwimuAfrica/TAKWIMU#95]
## Description
TBD: Requirements regarding security or privacy issues surrounding use of the product or protection of the data used or created by the product. Define any user identity authentication requirements. Refer to any external policies or regulations containing security issues that affect the product. Define any security or privacy certifications that must be satisfied.

## Files
A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.

## To Reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.

## Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

[https://docs.google.com/document/d/1Vvd2WukWxkkpM7qhHvGD49DzeZfwAluo3jxfJzT2NbQ/edit?ts=5afab7a5#heading=h.3whwml4](url)

**Comment by mtuchi** [comment]
Moving the issue back to trello board
