### ISSUE TITLE
[DOCUMENTATION] SRS - Safety Requirements

### ISSUE THREAD

**Issue by yazminjumaali** [TakwimuAfrica/TAKWIMU#96]
## Description
TBD: Requirements that are concerned with possible loss, damage, or harm that could result from the use of the product. Define any safeguards or actions that must be taken, as well as actions that must be prevented. Refer to any external policies or regulations that state safety issues that affect the product’s design or use. Define any safety certifications that must be satisfied.

## Files
A list of relevant files for this issue. This will help people navigate the project and offer some clues of where to start.

## To Reproduce
If this issue is describing a bug, include some steps to reproduce the behavior.

## Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Task 1
- [ ] Task 2
- [ ] Task 3

[https://docs.google.com/document/d/1Vvd2WukWxkkpM7qhHvGD49DzeZfwAluo3jxfJzT2NbQ/edit#](url)

**Comment by mtuchi** [comment]
Moved back to trello board
